#cloud-config
autoinstall:
 version: 1
 interactive-sections:
  - network
 storage:
  layout:
   name: lvm
   policy: all
 user-data:
  users: ['']
 locale: "de_CH.UTF-8"
 keyboard:
  layout: "ch"
 source:
  search_drivers: true
  id: ubuntu-desktop-minimal
 ssh:
  install-server: true
  allow-pw: true
 drivers:
  install: true
 packages:
  - openssh-server
 timezone: "Europe/Zurich"
 updates: all
 shutdown: reboot
 late-commands:
  - curtin in-target -- apt-get update
  - curtin in-target -- apt -y upgrade